name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ 14, 16 ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run test --if-present
      - run: npm run lint --if-present
      - run: npm run coverage --if-present


